services:
  db:
    image: postgres:18-alpine
    container_name: casdoor_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: casdoor
      POSTGRES_PASSWORD: Lug@2025!
      POSTGRES_DB: casdoor
    volumes:
      - ./pg_data:/var/lib/postgresql
    networks:
      - casdoor_net

  casdoor:
    image: casbin/casdoor:latest
    container_name: casdoor
    restart: unless-stopped
    ports:
      - "8002:8000"
    volumes:
      - ./conf:/conf
      - ./files:/files
    environment:
      - GIN_MODE=release
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - casdoor_net

networks:
  casdoor_net:
    driver: bridge
