// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

import type { Executor } from 'gel';

export type Seed_dataReturns = {
  id: string;
};

export function seed_data(client: Executor): Promise<Seed_dataReturns> {
  return client.queryRequiredSingle(`\
# ============================================================================
# EdgeDB Seed Data for Checklist System
# Generated from skeleton.xlsx data
# ============================================================================

# ============================================================================
# 1. INSERT EMPLOYEES
# ============================================================================
# Create employee with ID "1" and default email
insert Employee {
    employee_id := "1",
    email := "employee1@company.com"
};


# ============================================================================
# 2. INSERT CHECKLIST CATEGORIES (Parent items with is_category = true)
# ============================================================================

# Category 1: CHECK LIST HẰNG NGÀY (Daily Checklist)
insert ChecklistItem {
    name := "CHECK LIST HẰNG NGÀY",
    is_category := true,
    order := 1
};

# Category 2: CHECK LIST HẰNG TUẦN (Weekly Checklist)
insert ChecklistItem {
    name := "CHECK LIST HẰNG TUẦN",
    is_category := true,
    order := 2
};

# Category 3: CHECK LIST HẰNG THÁNG (Monthly Checklist)
insert ChecklistItem {
    name := "CHECK LIST HẰNG THÁNG",
    is_category := true,
    order := 3
};

# Category 4: XỬ LÝ KHI CÓ PHÁT SINH (Handle When Issues Arise)
insert ChecklistItem {
    name := "XỬ LÝ KHI CÓ PHÁT SINH",
    is_category := true,
    order := 4
};


# ============================================================================
# 3. INSERT CHECKLIST TASKS (Child items under categories)
# ============================================================================

# ---------- Tasks under "CHECK LIST HẰNG NGÀY" ----------
insert ChecklistItem {
    name := "Đánh giá sàng lọc những nhân sự có khả năng thăng tiến để tạo đội ngũ kế thừa; Tuyển dụng nhân sự thay thế.",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG NGÀY" limit 1),
    standard_score := 2,
    is_category := false,
    order := 1
};

insert ChecklistItem {
    name := "Đi làm đúng giờ, đúng lịch ca làm việc và lấy vân tay theo đúng quy định",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG NGÀY" limit 1),
    standard_score := 3,
    is_category := false,
    order := 2
};

insert ChecklistItem {
    name := "Đồng phục/ tác phong đúng quy định",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG NGÀY" limit 1),
    standard_score := 4,
    is_category := false,
    order := 3
};

insert ChecklistItem {
    name := "Kiểm soát việc thực hiện nội quy/quy định của NV",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG NGÀY" limit 1),
    standard_score := 5,
    is_category := false,
    order := 4
};

insert ChecklistItem {
    name := "Theo dõi chi phí quầy (đủ số lượng sử dụng tại CH/TT)",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG NGÀY" limit 1),
    standard_score := 5,
    is_category := false,
    order := 5
};


# ---------- Tasks under "CHECK LIST HẰNG TUẦN" ----------
insert ChecklistItem {
    name := "Theo dõi chỉ số điện, nước",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG TUẦN" limit 1),
    standard_score := 2,
    is_category := false,
    order := 1
};

insert ChecklistItem {
    name := "Họp nhân viên bán hàng/NT/CHT 01 lần/ tuần.",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG TUẦN" limit 1),
    standard_score := 2,
    is_category := false,
    order := 2
};

insert ChecklistItem {
    name := "Kiểm soát việc lưu trữ số sách giấy tờ, chứng từ, Giấy phép kinh doanh, Giấy phép PCCC.",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG TUẦN" limit 1),
    standard_score := 4,
    is_category := false,
    order := 3
};


# ---------- Tasks under "CHECK LIST HẰNG THÁNG" ----------
insert ChecklistItem {
    name := "Check lịch làm việc cho Nhân viên để đạt doanh thu.",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG THÁNG" limit 1),
    standard_score := 1,
    is_category := false,
    order := 1
};

insert ChecklistItem {
    name := "Đánh giá check list công việc của NV/NT/CHT",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG THÁNG" limit 1),
    standard_score := 2,
    is_category := false,
    order := 2
};

insert ChecklistItem {
    name := "Tuyển dụng và đào tạo nhân sự mới",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG THÁNG" limit 1),
    standard_score := 3,
    is_category := false,
    order := 3
};

insert ChecklistItem {
    name := "Kiểm tra báo cáo trình trạng hàng hóa hư hỏng về Cty. Đôn đốc các phòng ban",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG THÁNG" limit 1),
    standard_score := 4,
    is_category := false,
    order := 4
};

insert ChecklistItem {
    name := "Xác nhận thay tem/tag CTKM, báo cáo đầy đủ và kịp thời",
    parent := (select detached ChecklistItem filter .name = "CHECK LIST HẰNG THÁNG" limit 1),
    standard_score := 1,
    is_category := false,
    order := 5
};


# ---------- Tasks under "XỬ LÝ KHI CÓ PHÁT SINH" ----------
insert ChecklistItem {
    name := "Xử lý khiếu nại, đổi trả sản phẩm.",
    parent := (select detached ChecklistItem filter .name = "XỬ LÝ KHI CÓ PHÁT SINH" limit 1),
    standard_score := 1,
    is_category := false,
    order := 1
};

insert ChecklistItem {
    name := "Hỗ trợ thi công setup/ out quầy",
    parent := (select detached ChecklistItem filter .name = "XỬ LÝ KHI CÓ PHÁT SINH" limit 1),
    standard_score := 1,
    is_category := false,
    order := 2
};

insert ChecklistItem {
    name := "Báo cáo sự cố khi có phát sinh",
    parent := (select detached ChecklistItem filter .name = "XỬ LÝ KHI CÓ PHÁT SINH" limit 1),
    standard_score := 1,
    is_category := false,
    order := 3
};


# ============================================================================
# 4. CREATE A SHEET FOR THE EMPLOYEE
# ============================================================================
insert Sheet {
    employee := (select Employee filter .employee_id = "1" limit 1),
    name := "Employee 1 - January 2026 Checklist"
};


# ============================================================================
# 5. INSERT CHECKLIST RECORDS (Assessment data from Excel)
# ============================================================================
# Note: Only creating records for rows that have actual date values in the Excel file

# Record 1: Assessment on 2026-01-10
insert ChecklistRecord {
    sheet := (
        select Sheet
        filter .employee.employee_id = "1"
        and .name = "Employee 1 - January 2026 Checklist"
        limit 1
    ),
    checklist_item := (
        select detached ChecklistItem
        filter .name = "Đánh giá sàng lọc những nhân sự có khả năng thăng tiến để tạo đội ngũ kế thừa; Tuyển dụng nhân sự thay thế."
        limit 1
    ),
    employee := (select Employee filter .employee_id = "1" limit 1),
    assessment_date := <cal::local_date>'2026-01-10',
    employee_checked := true,
    cht_checked := true,
    asm_checked := true,
    final_classification := 'A'
};

# Record 2: Assessment on 2026-01-11
insert ChecklistRecord {
    sheet := (
        select Sheet
        filter .employee.employee_id = "1"
        and .name = "Employee 1 - January 2026 Checklist"
        limit 1
    ),
    checklist_item := (
        select detached ChecklistItem
        filter .name = "Đi làm đúng giờ, đúng lịch ca làm việc và lấy vân tay theo đúng quy định"
        limit 1
    ),
    employee := (select Employee filter .employee_id = "1" limit 1),
    assessment_date := <cal::local_date>'2026-01-11',
    employee_checked := true,
    cht_checked := true,
    asm_checked := true,
    final_classification := 'B'
};

# Record 3: Assessment on 2026-01-12
# Note: Employee ID is None in Excel, but we'll still create record for employee "1"
insert ChecklistRecord {
    sheet := (
        select Sheet
        filter .employee.employee_id = "1"
        and .name = "Employee 1 - January 2026 Checklist"
        limit 1
    ),
    checklist_item := (
        select detached ChecklistItem
        filter .name = "Đồng phục/ tác phong đúng quy định"
        limit 1
    ),
    employee := (select Employee filter .employee_id = "1" limit 1),
    assessment_date := <cal::local_date>'2026-01-12',
    employee_checked := false,
    cht_checked := false,
    asm_checked := false,
    final_classification := 'C'
};

# Record 4: Assessment on 2026-01-13
insert ChecklistRecord {
    sheet := (
        select Sheet
        filter .employee.employee_id = "1"
        and .name = "Employee 1 - January 2026 Checklist"
        limit 1
    ),
    checklist_item := (
        select detached ChecklistItem
        filter .name = "Kiểm soát việc thực hiện nội quy/quy định của NV"
        limit 1
    ),
    employee := (select Employee filter .employee_id = "1" limit 1),
    assessment_date := <cal::local_date>'2026-01-13',
    employee_checked := false,
    cht_checked := false,
    asm_checked := false,
    final_classification := 'D'
};

# Record 5: Assessment on 2026-01-14
insert ChecklistRecord {
    sheet := (
        select Sheet
        filter .employee.employee_id = "1"
        and .name = "Employee 1 - January 2026 Checklist"
        limit 1
    ),
    checklist_item := (
        select detached ChecklistItem
        filter .name = "Theo dõi chi phí quầy (đủ số lượng sử dụng tại CH/TT)"
        limit 1
    ),
    employee := (select Employee filter .employee_id = "1" limit 1),
    assessment_date := <cal::local_date>'2026-01-14',
    employee_checked := false,
    cht_checked := false,
    asm_checked := false
};


# ============================================================================
# VERIFICATION QUERIES (Optional - can be run separately to verify data)
# ============================================================================
# Uncomment these to verify your data after seeding:

# # Check all employees
# select Employee { employee_id, email };

# # Check all categories
# select ChecklistItem {
#     name,
#     is_category,
#     order,
#     standard_score
# }
# filter .is_category = true
# order by .order;

# # Check all tasks with their parent categories
# select ChecklistItem {
#     name,
#     standard_score,
#     order,
#     parent: { name }
# }
# filter .is_category = false
# order by .parent.order then .order;

# # Check all sheets
# select Sheet {
#     name,
#     employee: { employee_id, email },
#     created_at
# };

# # Check all checklist records
# select ChecklistRecord {
#     assessment_date,
#     employee: { employee_id },
#     checklist_item: { name },
#     employee_checked,
#     cht_checked,
#     asm_checked,
#     final_classification,
#     sheet: { name }
# }
# order by .assessment_date;`);
}
